
networks:
  lms_network:

services:
    LMS_DB:
        container_name: lms_db
        image:  mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 1533:1533
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=sqlserver@123  
        networks:
            - lms_network 
    lms:
        container_name: lms_web
        image: ${DOCKER_REGISTRY-}lms
        build:
            context: .
            dockerfile: LMS/Dockerfile
        ports: 
            - 8080:8080
            - 8081:8081
        depends_on:
            - LMS_DB
        environment:
            - DB_HOST=LMS_DB
            - DB_PORT=1433
            - DB_USER=sa
            - DB_PASSWORD=YourStrong@Passw0rd
            - DB_NAME=lms_db
        networks:
            - lms_network